[project]
name = "sentinel-10"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Siddhesh Kasar", email = "ksiddhesh96.sk@gmail.com" }
]
requires-python = ">=3.10,<3.14"
dependencies = [
    "anthropic>=0.122.0",
    "beautifulsoup4>=4.15.0",
    "datasets>=5.0.1",
    "deepeval>=4.1.8",
    "fastapi>=0.141.1",
    "jupyter>=1.1.1",
    "langfuse==2.60.2",
    "langgraph>=1.2.11",
    "lxml>=6.1.1",
    "pgvector>=0.5.0",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "sentence-transformers>=5.7.0",
    "streamlit>=1.62.0",
    "tiktoken>=0.13.0",
    "transformers>=5.15.0",
    "uvicorn>=0.52.3",
]

[project.scripts]
sentinel-10 = "sentinel_10:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
